name: build_image
on:
  push:
    branches:
      - 'test'
      - 'develop'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: checkout
        uses: actions/checkout@v3
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        id: build_push
        run: |
          export release=$(grep -i "LABEL RELEASE" Dockerfile|awk '{print $2}'|cut -d\" -f2)
          export version=$(grep -i "LABEL VERSION" Dockerfile|awk '{print $2}'|cut -d\" -f2)
          export maintainer=$(grep -i "LABEL MAINTAINER" Dockerfile|awk '{print $2}'|cut -d\" -f2)
          export DOCKER_BUILDKIT=1
          docker build --pull --no-cache -t  "$maintainer/$release":"$version" .
          docker image inspect "$maintainer/$release":"$version"
          docker tag "$maintainer/$release":"$version" "$maintainer/$release":"$version"-nightly
          docker push "$maintainer/$release":"$version"-nightly
